<?php
/**
 * CreateDm200Response
 *
 * PHP version 8.1
 *
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * @generated Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.2.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use OpenAPI\Client\ObjectSerializer;

/**
 * CreateDm200Response Class Doc Comment
 *
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class CreateDm200Response implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static string $openAPIModelName = 'create_dm_200_response';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var array<string, string>
      */
    protected static array $openAPITypes = [
        'id' => 'mixed',
        'type' => '\OpenAPI\Client\Model\ChannelTypes',
        'last_message_id' => 'mixed',
        'flags' => 'mixed',
        'last_pin_timestamp' => 'mixed',
        'recipients' => 'mixed',
        'name' => 'mixed',
        'icon' => 'mixed',
        'owner_id' => 'mixed',
        'managed' => 'mixed',
        'application_id' => 'mixed'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<string, string|null>
      */
    protected static array $openAPIFormats = [
        'id' => 'snowflake',
        'type' => null,
        'last_message_id' => 'snowflake',
        'flags' => 'int32',
        'last_pin_timestamp' => 'date-time',
        'recipients' => null,
        'name' => null,
        'icon' => null,
        'owner_id' => 'snowflake',
        'managed' => null,
        'application_id' => 'snowflake'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var array<string, bool>
      */
    protected static array $openAPINullables = [
        'id' => true,
		'type' => true,
		'last_message_id' => true,
		'flags' => true,
		'last_pin_timestamp' => true,
		'recipients' => true,
		'name' => true,
		'icon' => true,
		'owner_id' => true,
		'managed' => true,
		'application_id' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var array<string, bool>
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'id' => 'id',
        'type' => 'type',
        'last_message_id' => 'last_message_id',
        'flags' => 'flags',
        'last_pin_timestamp' => 'last_pin_timestamp',
        'recipients' => 'recipients',
        'name' => 'name',
        'icon' => 'icon',
        'owner_id' => 'owner_id',
        'managed' => 'managed',
        'application_id' => 'application_id'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'id' => 'setId',
        'type' => 'setType',
        'last_message_id' => 'setLastMessageId',
        'flags' => 'setFlags',
        'last_pin_timestamp' => 'setLastPinTimestamp',
        'recipients' => 'setRecipients',
        'name' => 'setName',
        'icon' => 'setIcon',
        'owner_id' => 'setOwnerId',
        'managed' => 'setManaged',
        'application_id' => 'setApplicationId'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'id' => 'getId',
        'type' => 'getType',
        'last_message_id' => 'getLastMessageId',
        'flags' => 'getFlags',
        'last_pin_timestamp' => 'getLastPinTimestamp',
        'recipients' => 'getRecipients',
        'name' => 'getName',
        'icon' => 'getIcon',
        'owner_id' => 'getOwnerId',
        'managed' => 'getManaged',
        'application_id' => 'getApplicationId'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array<string, string>
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array<string, string>
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array<string, string>
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('type', $data ?? [], null);
        $this->setIfExists('last_message_id', $data ?? [], null);
        $this->setIfExists('flags', $data ?? [], null);
        $this->setIfExists('last_pin_timestamp', $data ?? [], null);
        $this->setIfExists('recipients', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('icon', $data ?? [], null);
        $this->setIfExists('owner_id', $data ?? [], null);
        $this->setIfExists('managed', $data ?? [], null);
        $this->setIfExists('application_id', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if (!preg_match("^(0|[1-9][0-9]*)$", $this->container['id'])) {
            $invalidProperties[] = "invalid value for 'id', must be conform to the pattern ^(0|[1-9][0-9]*)$.";
        }

        if ($this->container['type'] === null) {
            $invalidProperties[] = "'type' can't be null";
        }
        if (!is_null($this->container['last_message_id']) && !preg_match("^(0|[1-9][0-9]*)$", $this->container['last_message_id'])) {
            $invalidProperties[] = "invalid value for 'last_message_id', must be conform to the pattern ^(0|[1-9][0-9]*)$.";
        }

        if ($this->container['flags'] === null) {
            $invalidProperties[] = "'flags' can't be null";
        }
        if ($this->container['recipients'] === null) {
            $invalidProperties[] = "'recipients' can't be null";
        }
        if (!is_null($this->container['owner_id']) && !preg_match("^(0|[1-9][0-9]*)$", $this->container['owner_id'])) {
            $invalidProperties[] = "invalid value for 'owner_id', must be conform to the pattern ^(0|[1-9][0-9]*)$.";
        }

        if (!is_null($this->container['application_id']) && !preg_match("^(0|[1-9][0-9]*)$", $this->container['application_id'])) {
            $invalidProperties[] = "invalid value for 'application_id', must be conform to the pattern ^(0|[1-9][0-9]*)$.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return mixed
     */
    public function getId(): mixed
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param mixed $id id
     *
     * @return $this
     */
    public function setId(mixed $id): static
    {
        if (is_null($id)) {
            array_push($this->openAPINullablesSetToNull, 'id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($id) && (!preg_match("^(0|[1-9][0-9]*)$", ObjectSerializer::toString($id)))) {
            throw new InvalidArgumentException("invalid value for \$id when calling CreateDm200Response., must conform to the pattern ^(0|[1-9][0-9]*)$.");
        }

        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets type
     *
     * @return \OpenAPI\Client\Model\ChannelTypes
     */
    public function getType(): ?\OpenAPI\Client\Model\ChannelTypes
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param \OpenAPI\Client\Model\ChannelTypes $type type
     *
     * @return $this
     */
    public function setType(?\OpenAPI\Client\Model\ChannelTypes $type): static
    {
        if (is_null($type)) {
            array_push($this->openAPINullablesSetToNull, 'type');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('type', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets last_message_id
     *
     * @return mixed|null
     */
    public function getLastMessageId(): mixed
    {
        return $this->container['last_message_id'];
    }

    /**
     * Sets last_message_id
     *
     * @param mixed|null $last_message_id last_message_id
     *
     * @return $this
     */
    public function setLastMessageId(mixed $last_message_id): static
    {
        if (is_null($last_message_id)) {
            array_push($this->openAPINullablesSetToNull, 'last_message_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('last_message_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($last_message_id) && (!preg_match("^(0|[1-9][0-9]*)$", ObjectSerializer::toString($last_message_id)))) {
            throw new InvalidArgumentException("invalid value for \$last_message_id when calling CreateDm200Response., must conform to the pattern ^(0|[1-9][0-9]*)$.");
        }

        $this->container['last_message_id'] = $last_message_id;

        return $this;
    }

    /**
     * Gets flags
     *
     * @return mixed
     */
    public function getFlags(): mixed
    {
        return $this->container['flags'];
    }

    /**
     * Sets flags
     *
     * @param mixed $flags flags
     *
     * @return $this
     */
    public function setFlags(mixed $flags): static
    {
        if (is_null($flags)) {
            array_push($this->openAPINullablesSetToNull, 'flags');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('flags', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['flags'] = $flags;

        return $this;
    }

    /**
     * Gets last_pin_timestamp
     *
     * @return mixed|null
     */
    public function getLastPinTimestamp(): mixed
    {
        return $this->container['last_pin_timestamp'];
    }

    /**
     * Sets last_pin_timestamp
     *
     * @param mixed|null $last_pin_timestamp last_pin_timestamp
     *
     * @return $this
     */
    public function setLastPinTimestamp(mixed $last_pin_timestamp): static
    {
        if (is_null($last_pin_timestamp)) {
            array_push($this->openAPINullablesSetToNull, 'last_pin_timestamp');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('last_pin_timestamp', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['last_pin_timestamp'] = $last_pin_timestamp;

        return $this;
    }

    /**
     * Gets recipients
     *
     * @return mixed
     */
    public function getRecipients(): mixed
    {
        return $this->container['recipients'];
    }

    /**
     * Sets recipients
     *
     * @param mixed $recipients recipients
     *
     * @return $this
     */
    public function setRecipients(mixed $recipients): static
    {
        if (is_null($recipients)) {
            array_push($this->openAPINullablesSetToNull, 'recipients');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('recipients', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['recipients'] = $recipients;

        return $this;
    }

    /**
     * Gets name
     *
     * @return mixed|null
     */
    public function getName(): mixed
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param mixed|null $name name
     *
     * @return $this
     */
    public function setName(mixed $name): static
    {
        if (is_null($name)) {
            array_push($this->openAPINullablesSetToNull, 'name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets icon
     *
     * @return mixed|null
     */
    public function getIcon(): mixed
    {
        return $this->container['icon'];
    }

    /**
     * Sets icon
     *
     * @param mixed|null $icon icon
     *
     * @return $this
     */
    public function setIcon(mixed $icon): static
    {
        if (is_null($icon)) {
            array_push($this->openAPINullablesSetToNull, 'icon');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('icon', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['icon'] = $icon;

        return $this;
    }

    /**
     * Gets owner_id
     *
     * @return mixed|null
     */
    public function getOwnerId(): mixed
    {
        return $this->container['owner_id'];
    }

    /**
     * Sets owner_id
     *
     * @param mixed|null $owner_id owner_id
     *
     * @return $this
     */
    public function setOwnerId(mixed $owner_id): static
    {
        if (is_null($owner_id)) {
            array_push($this->openAPINullablesSetToNull, 'owner_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('owner_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($owner_id) && (!preg_match("^(0|[1-9][0-9]*)$", ObjectSerializer::toString($owner_id)))) {
            throw new InvalidArgumentException("invalid value for \$owner_id when calling CreateDm200Response., must conform to the pattern ^(0|[1-9][0-9]*)$.");
        }

        $this->container['owner_id'] = $owner_id;

        return $this;
    }

    /**
     * Gets managed
     *
     * @return mixed|null
     */
    public function getManaged(): mixed
    {
        return $this->container['managed'];
    }

    /**
     * Sets managed
     *
     * @param mixed|null $managed managed
     *
     * @return $this
     */
    public function setManaged(mixed $managed): static
    {
        if (is_null($managed)) {
            array_push($this->openAPINullablesSetToNull, 'managed');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('managed', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['managed'] = $managed;

        return $this;
    }

    /**
     * Gets application_id
     *
     * @return mixed|null
     */
    public function getApplicationId(): mixed
    {
        return $this->container['application_id'];
    }

    /**
     * Sets application_id
     *
     * @param mixed|null $application_id application_id
     *
     * @return $this
     */
    public function setApplicationId(mixed $application_id): static
    {
        if (is_null($application_id)) {
            array_push($this->openAPINullablesSetToNull, 'application_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('application_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($application_id) && (!preg_match("^(0|[1-9][0-9]*)$", ObjectSerializer::toString($application_id)))) {
            throw new InvalidArgumentException("invalid value for \$application_id when calling CreateDm200Response., must conform to the pattern ^(0|[1-9][0-9]*)$.");
        }

        $this->container['application_id'] = $application_id;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


