<?php
/**
 * CreateGuildChannelRequest
 *
 * PHP version 8.1
 *
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * @generated Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.2.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use OpenAPI\Client\ObjectSerializer;

/**
 * CreateGuildChannelRequest Class Doc Comment
 *
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class CreateGuildChannelRequest implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static string $openAPIModelName = 'CreateGuildChannelRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var array<string, string>
      */
    protected static array $openAPITypes = [
        'type' => 'OneOf',
        'name' => 'string',
        'position' => 'int',
        'topic' => 'string',
        'bitrate' => 'int',
        'user_limit' => 'int',
        'nsfw' => 'bool',
        'rate_limit_per_user' => 'int',
        'parent_id' => 'string',
        'permission_overwrites' => '\OpenAPI\Client\Model\ChannelPermissionOverwriteRequest[]',
        'rtc_region' => 'string',
        'video_quality_mode' => '\OpenAPI\Client\Model\VideoQualityModes',
        'default_auto_archive_duration' => '\OpenAPI\Client\Model\ThreadAutoArchiveDuration',
        'default_reaction_emoji' => '\OpenAPI\Client\Model\UpdateDefaultReactionEmojiRequest',
        'default_thread_rate_limit_per_user' => 'int',
        'default_sort_order' => '\OpenAPI\Client\Model\ThreadSortOrder',
        'default_forum_layout' => '\OpenAPI\Client\Model\ForumLayout',
        'available_tags' => '\OpenAPI\Client\Model\CreateOrUpdateThreadTagRequest[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<string, string|null>
      */
    protected static array $openAPIFormats = [
        'type' => null,
        'name' => null,
        'position' => 'int32',
        'topic' => null,
        'bitrate' => 'int32',
        'user_limit' => 'int32',
        'nsfw' => null,
        'rate_limit_per_user' => null,
        'parent_id' => 'snowflake',
        'permission_overwrites' => null,
        'rtc_region' => null,
        'video_quality_mode' => null,
        'default_auto_archive_duration' => null,
        'default_reaction_emoji' => null,
        'default_thread_rate_limit_per_user' => null,
        'default_sort_order' => null,
        'default_forum_layout' => null,
        'available_tags' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var array<string, bool>
      */
    protected static array $openAPINullables = [
        'type' => true,
		'name' => false,
		'position' => true,
		'topic' => true,
		'bitrate' => true,
		'user_limit' => true,
		'nsfw' => true,
		'rate_limit_per_user' => true,
		'parent_id' => false,
		'permission_overwrites' => false,
		'rtc_region' => true,
		'video_quality_mode' => true,
		'default_auto_archive_duration' => true,
		'default_reaction_emoji' => true,
		'default_thread_rate_limit_per_user' => true,
		'default_sort_order' => true,
		'default_forum_layout' => true,
		'available_tags' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var array<string, bool>
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'type' => 'type',
        'name' => 'name',
        'position' => 'position',
        'topic' => 'topic',
        'bitrate' => 'bitrate',
        'user_limit' => 'user_limit',
        'nsfw' => 'nsfw',
        'rate_limit_per_user' => 'rate_limit_per_user',
        'parent_id' => 'parent_id',
        'permission_overwrites' => 'permission_overwrites',
        'rtc_region' => 'rtc_region',
        'video_quality_mode' => 'video_quality_mode',
        'default_auto_archive_duration' => 'default_auto_archive_duration',
        'default_reaction_emoji' => 'default_reaction_emoji',
        'default_thread_rate_limit_per_user' => 'default_thread_rate_limit_per_user',
        'default_sort_order' => 'default_sort_order',
        'default_forum_layout' => 'default_forum_layout',
        'available_tags' => 'available_tags'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'type' => 'setType',
        'name' => 'setName',
        'position' => 'setPosition',
        'topic' => 'setTopic',
        'bitrate' => 'setBitrate',
        'user_limit' => 'setUserLimit',
        'nsfw' => 'setNsfw',
        'rate_limit_per_user' => 'setRateLimitPerUser',
        'parent_id' => 'setParentId',
        'permission_overwrites' => 'setPermissionOverwrites',
        'rtc_region' => 'setRtcRegion',
        'video_quality_mode' => 'setVideoQualityMode',
        'default_auto_archive_duration' => 'setDefaultAutoArchiveDuration',
        'default_reaction_emoji' => 'setDefaultReactionEmoji',
        'default_thread_rate_limit_per_user' => 'setDefaultThreadRateLimitPerUser',
        'default_sort_order' => 'setDefaultSortOrder',
        'default_forum_layout' => 'setDefaultForumLayout',
        'available_tags' => 'setAvailableTags'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'type' => 'getType',
        'name' => 'getName',
        'position' => 'getPosition',
        'topic' => 'getTopic',
        'bitrate' => 'getBitrate',
        'user_limit' => 'getUserLimit',
        'nsfw' => 'getNsfw',
        'rate_limit_per_user' => 'getRateLimitPerUser',
        'parent_id' => 'getParentId',
        'permission_overwrites' => 'getPermissionOverwrites',
        'rtc_region' => 'getRtcRegion',
        'video_quality_mode' => 'getVideoQualityMode',
        'default_auto_archive_duration' => 'getDefaultAutoArchiveDuration',
        'default_reaction_emoji' => 'getDefaultReactionEmoji',
        'default_thread_rate_limit_per_user' => 'getDefaultThreadRateLimitPerUser',
        'default_sort_order' => 'getDefaultSortOrder',
        'default_forum_layout' => 'getDefaultForumLayout',
        'available_tags' => 'getAvailableTags'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array<string, string>
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array<string, string>
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array<string, string>
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('type', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('position', $data ?? [], null);
        $this->setIfExists('topic', $data ?? [], null);
        $this->setIfExists('bitrate', $data ?? [], null);
        $this->setIfExists('user_limit', $data ?? [], null);
        $this->setIfExists('nsfw', $data ?? [], null);
        $this->setIfExists('rate_limit_per_user', $data ?? [], null);
        $this->setIfExists('parent_id', $data ?? [], null);
        $this->setIfExists('permission_overwrites', $data ?? [], null);
        $this->setIfExists('rtc_region', $data ?? [], null);
        $this->setIfExists('video_quality_mode', $data ?? [], null);
        $this->setIfExists('default_auto_archive_duration', $data ?? [], null);
        $this->setIfExists('default_reaction_emoji', $data ?? [], null);
        $this->setIfExists('default_thread_rate_limit_per_user', $data ?? [], null);
        $this->setIfExists('default_sort_order', $data ?? [], null);
        $this->setIfExists('default_forum_layout', $data ?? [], null);
        $this->setIfExists('available_tags', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ((mb_strlen($this->container['name']) > 100)) {
            $invalidProperties[] = "invalid value for 'name', the character length must be smaller than or equal to 100.";
        }

        if ((mb_strlen($this->container['name']) < 1)) {
            $invalidProperties[] = "invalid value for 'name', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['position']) && ($this->container['position'] < 0)) {
            $invalidProperties[] = "invalid value for 'position', must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['topic']) && (mb_strlen($this->container['topic']) > 4096)) {
            $invalidProperties[] = "invalid value for 'topic', the character length must be smaller than or equal to 4096.";
        }

        if (!is_null($this->container['topic']) && (mb_strlen($this->container['topic']) < 0)) {
            $invalidProperties[] = "invalid value for 'topic', the character length must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['bitrate']) && ($this->container['bitrate'] < 8000)) {
            $invalidProperties[] = "invalid value for 'bitrate', must be bigger than or equal to 8000.";
        }

        if (!is_null($this->container['user_limit']) && ($this->container['user_limit'] < 0)) {
            $invalidProperties[] = "invalid value for 'user_limit', must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['rate_limit_per_user']) && ($this->container['rate_limit_per_user'] > 21600)) {
            $invalidProperties[] = "invalid value for 'rate_limit_per_user', must be smaller than or equal to 21600.";
        }

        if (!is_null($this->container['rate_limit_per_user']) && ($this->container['rate_limit_per_user'] < 0)) {
            $invalidProperties[] = "invalid value for 'rate_limit_per_user', must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['parent_id']) && !preg_match("/^(0|[1-9][0-9]*)$/", $this->container['parent_id'])) {
            $invalidProperties[] = "invalid value for 'parent_id', must be conform to the pattern /^(0|[1-9][0-9]*)$/.";
        }

        if (!is_null($this->container['default_thread_rate_limit_per_user']) && ($this->container['default_thread_rate_limit_per_user'] > 21600)) {
            $invalidProperties[] = "invalid value for 'default_thread_rate_limit_per_user', must be smaller than or equal to 21600.";
        }

        if (!is_null($this->container['default_thread_rate_limit_per_user']) && ($this->container['default_thread_rate_limit_per_user'] < 0)) {
            $invalidProperties[] = "invalid value for 'default_thread_rate_limit_per_user', must be bigger than or equal to 0.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets type
     *
     * @return OneOf|null
     */
    public function getType(): ?OneOf
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param OneOf|null $type type
     *
     * @return $this
     */
    public function setType(?OneOf $type): static
    {
        if (is_null($type)) {
            array_push($this->openAPINullablesSetToNull, 'type');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('type', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName(): string
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name name
     *
     * @return $this
     */
    public function setName(string $name): static
    {
        if (is_null($name)) {
            throw new InvalidArgumentException('non-nullable name cannot be null');
        }
        if ((mb_strlen($name) > 100)) {
            throw new InvalidArgumentException('invalid length for $name when calling CreateGuildChannelRequest., must be smaller than or equal to 100.');
        }
        if ((mb_strlen($name) < 1)) {
            throw new InvalidArgumentException('invalid length for $name when calling CreateGuildChannelRequest., must be bigger than or equal to 1.');
        }

        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets position
     *
     * @return int|null
     */
    public function getPosition(): ?int
    {
        return $this->container['position'];
    }

    /**
     * Sets position
     *
     * @param int|null $position position
     *
     * @return $this
     */
    public function setPosition(?int $position): static
    {
        if (is_null($position)) {
            array_push($this->openAPINullablesSetToNull, 'position');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('position', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($position) && ($position < 0)) {
            throw new InvalidArgumentException('invalid value for $position when calling CreateGuildChannelRequest., must be bigger than or equal to 0.');
        }

        $this->container['position'] = $position;

        return $this;
    }

    /**
     * Gets topic
     *
     * @return string|null
     */
    public function getTopic(): ?string
    {
        return $this->container['topic'];
    }

    /**
     * Sets topic
     *
     * @param string|null $topic topic
     *
     * @return $this
     */
    public function setTopic(?string $topic): static
    {
        if (is_null($topic)) {
            array_push($this->openAPINullablesSetToNull, 'topic');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('topic', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($topic) && (mb_strlen($topic) > 4096)) {
            throw new InvalidArgumentException('invalid length for $topic when calling CreateGuildChannelRequest., must be smaller than or equal to 4096.');
        }
        if (!is_null($topic) && (mb_strlen($topic) < 0)) {
            throw new InvalidArgumentException('invalid length for $topic when calling CreateGuildChannelRequest., must be bigger than or equal to 0.');
        }

        $this->container['topic'] = $topic;

        return $this;
    }

    /**
     * Gets bitrate
     *
     * @return int|null
     */
    public function getBitrate(): ?int
    {
        return $this->container['bitrate'];
    }

    /**
     * Sets bitrate
     *
     * @param int|null $bitrate bitrate
     *
     * @return $this
     */
    public function setBitrate(?int $bitrate): static
    {
        if (is_null($bitrate)) {
            array_push($this->openAPINullablesSetToNull, 'bitrate');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('bitrate', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($bitrate) && ($bitrate < 8000)) {
            throw new InvalidArgumentException('invalid value for $bitrate when calling CreateGuildChannelRequest., must be bigger than or equal to 8000.');
        }

        $this->container['bitrate'] = $bitrate;

        return $this;
    }

    /**
     * Gets user_limit
     *
     * @return int|null
     */
    public function getUserLimit(): ?int
    {
        return $this->container['user_limit'];
    }

    /**
     * Sets user_limit
     *
     * @param int|null $user_limit user_limit
     *
     * @return $this
     */
    public function setUserLimit(?int $user_limit): static
    {
        if (is_null($user_limit)) {
            array_push($this->openAPINullablesSetToNull, 'user_limit');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('user_limit', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($user_limit) && ($user_limit < 0)) {
            throw new InvalidArgumentException('invalid value for $user_limit when calling CreateGuildChannelRequest., must be bigger than or equal to 0.');
        }

        $this->container['user_limit'] = $user_limit;

        return $this;
    }

    /**
     * Gets nsfw
     *
     * @return bool|null
     */
    public function getNsfw(): ?bool
    {
        return $this->container['nsfw'];
    }

    /**
     * Sets nsfw
     *
     * @param bool|null $nsfw nsfw
     *
     * @return $this
     */
    public function setNsfw(?bool $nsfw): static
    {
        if (is_null($nsfw)) {
            array_push($this->openAPINullablesSetToNull, 'nsfw');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('nsfw', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['nsfw'] = $nsfw;

        return $this;
    }

    /**
     * Gets rate_limit_per_user
     *
     * @return int|null
     */
    public function getRateLimitPerUser(): ?int
    {
        return $this->container['rate_limit_per_user'];
    }

    /**
     * Sets rate_limit_per_user
     *
     * @param int|null $rate_limit_per_user rate_limit_per_user
     *
     * @return $this
     */
    public function setRateLimitPerUser(?int $rate_limit_per_user): static
    {
        if (is_null($rate_limit_per_user)) {
            array_push($this->openAPINullablesSetToNull, 'rate_limit_per_user');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('rate_limit_per_user', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($rate_limit_per_user) && ($rate_limit_per_user > 21600)) {
            throw new InvalidArgumentException('invalid value for $rate_limit_per_user when calling CreateGuildChannelRequest., must be smaller than or equal to 21600.');
        }
        if (!is_null($rate_limit_per_user) && ($rate_limit_per_user < 0)) {
            throw new InvalidArgumentException('invalid value for $rate_limit_per_user when calling CreateGuildChannelRequest., must be bigger than or equal to 0.');
        }

        $this->container['rate_limit_per_user'] = $rate_limit_per_user;

        return $this;
    }

    /**
     * Gets parent_id
     *
     * @return string|null
     */
    public function getParentId(): ?string
    {
        return $this->container['parent_id'];
    }

    /**
     * Sets parent_id
     *
     * @param string|null $parent_id parent_id
     *
     * @return $this
     */
    public function setParentId(?string $parent_id): static
    {
        if (is_null($parent_id)) {
            throw new InvalidArgumentException('non-nullable parent_id cannot be null');
        }

        if ((!preg_match("/^(0|[1-9][0-9]*)$/", ObjectSerializer::toString($parent_id)))) {
            throw new InvalidArgumentException("invalid value for \$parent_id when calling CreateGuildChannelRequest., must conform to the pattern /^(0|[1-9][0-9]*)$/.");
        }

        $this->container['parent_id'] = $parent_id;

        return $this;
    }

    /**
     * Gets permission_overwrites
     *
     * @return \OpenAPI\Client\Model\ChannelPermissionOverwriteRequest[]|null
     */
    public function getPermissionOverwrites(): ?array
    {
        return $this->container['permission_overwrites'];
    }

    /**
     * Sets permission_overwrites
     *
     * @param \OpenAPI\Client\Model\ChannelPermissionOverwriteRequest[]|null $permission_overwrites permission_overwrites
     *
     * @return $this
     */
    public function setPermissionOverwrites(?array $permission_overwrites): static
    {
        if (is_null($permission_overwrites)) {
            throw new InvalidArgumentException('non-nullable permission_overwrites cannot be null');
        }
        $this->container['permission_overwrites'] = $permission_overwrites;

        return $this;
    }

    /**
     * Gets rtc_region
     *
     * @return string|null
     */
    public function getRtcRegion(): ?string
    {
        return $this->container['rtc_region'];
    }

    /**
     * Sets rtc_region
     *
     * @param string|null $rtc_region rtc_region
     *
     * @return $this
     */
    public function setRtcRegion(?string $rtc_region): static
    {
        if (is_null($rtc_region)) {
            array_push($this->openAPINullablesSetToNull, 'rtc_region');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('rtc_region', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['rtc_region'] = $rtc_region;

        return $this;
    }

    /**
     * Gets video_quality_mode
     *
     * @return \OpenAPI\Client\Model\VideoQualityModes|null
     */
    public function getVideoQualityMode(): ?\OpenAPI\Client\Model\VideoQualityModes
    {
        return $this->container['video_quality_mode'];
    }

    /**
     * Sets video_quality_mode
     *
     * @param \OpenAPI\Client\Model\VideoQualityModes|null $video_quality_mode video_quality_mode
     *
     * @return $this
     */
    public function setVideoQualityMode(?\OpenAPI\Client\Model\VideoQualityModes $video_quality_mode): static
    {
        if (is_null($video_quality_mode)) {
            array_push($this->openAPINullablesSetToNull, 'video_quality_mode');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('video_quality_mode', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['video_quality_mode'] = $video_quality_mode;

        return $this;
    }

    /**
     * Gets default_auto_archive_duration
     *
     * @return \OpenAPI\Client\Model\ThreadAutoArchiveDuration|null
     */
    public function getDefaultAutoArchiveDuration(): ?\OpenAPI\Client\Model\ThreadAutoArchiveDuration
    {
        return $this->container['default_auto_archive_duration'];
    }

    /**
     * Sets default_auto_archive_duration
     *
     * @param \OpenAPI\Client\Model\ThreadAutoArchiveDuration|null $default_auto_archive_duration default_auto_archive_duration
     *
     * @return $this
     */
    public function setDefaultAutoArchiveDuration(?\OpenAPI\Client\Model\ThreadAutoArchiveDuration $default_auto_archive_duration): static
    {
        if (is_null($default_auto_archive_duration)) {
            array_push($this->openAPINullablesSetToNull, 'default_auto_archive_duration');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('default_auto_archive_duration', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['default_auto_archive_duration'] = $default_auto_archive_duration;

        return $this;
    }

    /**
     * Gets default_reaction_emoji
     *
     * @return \OpenAPI\Client\Model\UpdateDefaultReactionEmojiRequest|null
     */
    public function getDefaultReactionEmoji(): ?\OpenAPI\Client\Model\UpdateDefaultReactionEmojiRequest
    {
        return $this->container['default_reaction_emoji'];
    }

    /**
     * Sets default_reaction_emoji
     *
     * @param \OpenAPI\Client\Model\UpdateDefaultReactionEmojiRequest|null $default_reaction_emoji default_reaction_emoji
     *
     * @return $this
     */
    public function setDefaultReactionEmoji(?\OpenAPI\Client\Model\UpdateDefaultReactionEmojiRequest $default_reaction_emoji): static
    {
        if (is_null($default_reaction_emoji)) {
            array_push($this->openAPINullablesSetToNull, 'default_reaction_emoji');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('default_reaction_emoji', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['default_reaction_emoji'] = $default_reaction_emoji;

        return $this;
    }

    /**
     * Gets default_thread_rate_limit_per_user
     *
     * @return int|null
     */
    public function getDefaultThreadRateLimitPerUser(): ?int
    {
        return $this->container['default_thread_rate_limit_per_user'];
    }

    /**
     * Sets default_thread_rate_limit_per_user
     *
     * @param int|null $default_thread_rate_limit_per_user default_thread_rate_limit_per_user
     *
     * @return $this
     */
    public function setDefaultThreadRateLimitPerUser(?int $default_thread_rate_limit_per_user): static
    {
        if (is_null($default_thread_rate_limit_per_user)) {
            array_push($this->openAPINullablesSetToNull, 'default_thread_rate_limit_per_user');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('default_thread_rate_limit_per_user', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($default_thread_rate_limit_per_user) && ($default_thread_rate_limit_per_user > 21600)) {
            throw new InvalidArgumentException('invalid value for $default_thread_rate_limit_per_user when calling CreateGuildChannelRequest., must be smaller than or equal to 21600.');
        }
        if (!is_null($default_thread_rate_limit_per_user) && ($default_thread_rate_limit_per_user < 0)) {
            throw new InvalidArgumentException('invalid value for $default_thread_rate_limit_per_user when calling CreateGuildChannelRequest., must be bigger than or equal to 0.');
        }

        $this->container['default_thread_rate_limit_per_user'] = $default_thread_rate_limit_per_user;

        return $this;
    }

    /**
     * Gets default_sort_order
     *
     * @return \OpenAPI\Client\Model\ThreadSortOrder|null
     */
    public function getDefaultSortOrder(): ?\OpenAPI\Client\Model\ThreadSortOrder
    {
        return $this->container['default_sort_order'];
    }

    /**
     * Sets default_sort_order
     *
     * @param \OpenAPI\Client\Model\ThreadSortOrder|null $default_sort_order default_sort_order
     *
     * @return $this
     */
    public function setDefaultSortOrder(?\OpenAPI\Client\Model\ThreadSortOrder $default_sort_order): static
    {
        if (is_null($default_sort_order)) {
            array_push($this->openAPINullablesSetToNull, 'default_sort_order');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('default_sort_order', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['default_sort_order'] = $default_sort_order;

        return $this;
    }

    /**
     * Gets default_forum_layout
     *
     * @return \OpenAPI\Client\Model\ForumLayout|null
     */
    public function getDefaultForumLayout(): ?\OpenAPI\Client\Model\ForumLayout
    {
        return $this->container['default_forum_layout'];
    }

    /**
     * Sets default_forum_layout
     *
     * @param \OpenAPI\Client\Model\ForumLayout|null $default_forum_layout default_forum_layout
     *
     * @return $this
     */
    public function setDefaultForumLayout(?\OpenAPI\Client\Model\ForumLayout $default_forum_layout): static
    {
        if (is_null($default_forum_layout)) {
            array_push($this->openAPINullablesSetToNull, 'default_forum_layout');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('default_forum_layout', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['default_forum_layout'] = $default_forum_layout;

        return $this;
    }

    /**
     * Gets available_tags
     *
     * @return \OpenAPI\Client\Model\CreateOrUpdateThreadTagRequest[]|null
     */
    public function getAvailableTags(): ?array
    {
        return $this->container['available_tags'];
    }

    /**
     * Sets available_tags
     *
     * @param \OpenAPI\Client\Model\CreateOrUpdateThreadTagRequest[]|null $available_tags available_tags
     *
     * @return $this
     */
    public function setAvailableTags(?array $available_tags): static
    {
        if (is_null($available_tags)) {
            throw new InvalidArgumentException('non-nullable available_tags cannot be null');
        }
        $this->container['available_tags'] = $available_tags;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


