<?php
/**
 * GuildMemberResponse
 *
 * PHP version 8.1
 *
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * @generated Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.2.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use OpenAPI\Client\ObjectSerializer;

/**
 * GuildMemberResponse Class Doc Comment
 *
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class GuildMemberResponse implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static string $openAPIModelName = 'GuildMemberResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var array<string, string>
      */
    protected static array $openAPITypes = [
        'avatar' => 'string',
        'communication_disabled_until' => '\DateTime',
        'flags' => 'int',
        'joined_at' => '\DateTime',
        'nick' => 'string',
        'pending' => 'bool',
        'premium_since' => '\DateTime',
        'roles' => 'string[]',
        'user' => '\OpenAPI\Client\Model\UserResponse',
        'mute' => 'bool',
        'deaf' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<string, string|null>
      */
    protected static array $openAPIFormats = [
        'avatar' => null,
        'communication_disabled_until' => 'date-time',
        'flags' => 'int32',
        'joined_at' => 'date-time',
        'nick' => null,
        'pending' => null,
        'premium_since' => 'date-time',
        'roles' => 'snowflake',
        'user' => null,
        'mute' => null,
        'deaf' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var array<string, bool>
      */
    protected static array $openAPINullables = [
        'avatar' => true,
		'communication_disabled_until' => true,
		'flags' => false,
		'joined_at' => false,
		'nick' => true,
		'pending' => false,
		'premium_since' => true,
		'roles' => false,
		'user' => false,
		'mute' => false,
		'deaf' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var array<string, bool>
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'avatar' => 'avatar',
        'communication_disabled_until' => 'communication_disabled_until',
        'flags' => 'flags',
        'joined_at' => 'joined_at',
        'nick' => 'nick',
        'pending' => 'pending',
        'premium_since' => 'premium_since',
        'roles' => 'roles',
        'user' => 'user',
        'mute' => 'mute',
        'deaf' => 'deaf'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'avatar' => 'setAvatar',
        'communication_disabled_until' => 'setCommunicationDisabledUntil',
        'flags' => 'setFlags',
        'joined_at' => 'setJoinedAt',
        'nick' => 'setNick',
        'pending' => 'setPending',
        'premium_since' => 'setPremiumSince',
        'roles' => 'setRoles',
        'user' => 'setUser',
        'mute' => 'setMute',
        'deaf' => 'setDeaf'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'avatar' => 'getAvatar',
        'communication_disabled_until' => 'getCommunicationDisabledUntil',
        'flags' => 'getFlags',
        'joined_at' => 'getJoinedAt',
        'nick' => 'getNick',
        'pending' => 'getPending',
        'premium_since' => 'getPremiumSince',
        'roles' => 'getRoles',
        'user' => 'getUser',
        'mute' => 'getMute',
        'deaf' => 'getDeaf'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array<string, string>
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array<string, string>
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array<string, string>
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('avatar', $data ?? [], null);
        $this->setIfExists('communication_disabled_until', $data ?? [], null);
        $this->setIfExists('flags', $data ?? [], null);
        $this->setIfExists('joined_at', $data ?? [], null);
        $this->setIfExists('nick', $data ?? [], null);
        $this->setIfExists('pending', $data ?? [], null);
        $this->setIfExists('premium_since', $data ?? [], null);
        $this->setIfExists('roles', $data ?? [], null);
        $this->setIfExists('user', $data ?? [], null);
        $this->setIfExists('mute', $data ?? [], null);
        $this->setIfExists('deaf', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if ($this->container['flags'] === null) {
            $invalidProperties[] = "'flags' can't be null";
        }
        if ($this->container['joined_at'] === null) {
            $invalidProperties[] = "'joined_at' can't be null";
        }
        if ($this->container['pending'] === null) {
            $invalidProperties[] = "'pending' can't be null";
        }
        if ($this->container['roles'] === null) {
            $invalidProperties[] = "'roles' can't be null";
        }
        if ($this->container['user'] === null) {
            $invalidProperties[] = "'user' can't be null";
        }
        if ($this->container['mute'] === null) {
            $invalidProperties[] = "'mute' can't be null";
        }
        if ($this->container['deaf'] === null) {
            $invalidProperties[] = "'deaf' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets avatar
     *
     * @return string|null
     */
    public function getAvatar(): ?string
    {
        return $this->container['avatar'];
    }

    /**
     * Sets avatar
     *
     * @param string|null $avatar avatar
     *
     * @return $this
     */
    public function setAvatar(?string $avatar): static
    {
        if (is_null($avatar)) {
            array_push($this->openAPINullablesSetToNull, 'avatar');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('avatar', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['avatar'] = $avatar;

        return $this;
    }

    /**
     * Gets communication_disabled_until
     *
     * @return \DateTime|null
     */
    public function getCommunicationDisabledUntil(): ?\DateTime
    {
        return $this->container['communication_disabled_until'];
    }

    /**
     * Sets communication_disabled_until
     *
     * @param \DateTime|null $communication_disabled_until communication_disabled_until
     *
     * @return $this
     */
    public function setCommunicationDisabledUntil(?\DateTime $communication_disabled_until): static
    {
        if (is_null($communication_disabled_until)) {
            array_push($this->openAPINullablesSetToNull, 'communication_disabled_until');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('communication_disabled_until', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['communication_disabled_until'] = $communication_disabled_until;

        return $this;
    }

    /**
     * Gets flags
     *
     * @return int
     */
    public function getFlags(): int
    {
        return $this->container['flags'];
    }

    /**
     * Sets flags
     *
     * @param int $flags flags
     *
     * @return $this
     */
    public function setFlags(int $flags): static
    {
        if (is_null($flags)) {
            throw new InvalidArgumentException('non-nullable flags cannot be null');
        }
        $this->container['flags'] = $flags;

        return $this;
    }

    /**
     * Gets joined_at
     *
     * @return \DateTime
     */
    public function getJoinedAt(): \DateTime
    {
        return $this->container['joined_at'];
    }

    /**
     * Sets joined_at
     *
     * @param \DateTime $joined_at joined_at
     *
     * @return $this
     */
    public function setJoinedAt(\DateTime $joined_at): static
    {
        if (is_null($joined_at)) {
            throw new InvalidArgumentException('non-nullable joined_at cannot be null');
        }
        $this->container['joined_at'] = $joined_at;

        return $this;
    }

    /**
     * Gets nick
     *
     * @return string|null
     */
    public function getNick(): ?string
    {
        return $this->container['nick'];
    }

    /**
     * Sets nick
     *
     * @param string|null $nick nick
     *
     * @return $this
     */
    public function setNick(?string $nick): static
    {
        if (is_null($nick)) {
            array_push($this->openAPINullablesSetToNull, 'nick');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('nick', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['nick'] = $nick;

        return $this;
    }

    /**
     * Gets pending
     *
     * @return bool
     */
    public function getPending(): bool
    {
        return $this->container['pending'];
    }

    /**
     * Sets pending
     *
     * @param bool $pending pending
     *
     * @return $this
     */
    public function setPending(bool $pending): static
    {
        if (is_null($pending)) {
            throw new InvalidArgumentException('non-nullable pending cannot be null');
        }
        $this->container['pending'] = $pending;

        return $this;
    }

    /**
     * Gets premium_since
     *
     * @return \DateTime|null
     */
    public function getPremiumSince(): ?\DateTime
    {
        return $this->container['premium_since'];
    }

    /**
     * Sets premium_since
     *
     * @param \DateTime|null $premium_since premium_since
     *
     * @return $this
     */
    public function setPremiumSince(?\DateTime $premium_since): static
    {
        if (is_null($premium_since)) {
            array_push($this->openAPINullablesSetToNull, 'premium_since');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('premium_since', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['premium_since'] = $premium_since;

        return $this;
    }

    /**
     * Gets roles
     *
     * @return string[]
     */
    public function getRoles(): array
    {
        return $this->container['roles'];
    }

    /**
     * Sets roles
     *
     * @param string[] $roles roles
     *
     * @return $this
     */
    public function setRoles(array $roles): static
    {
        if (is_null($roles)) {
            throw new InvalidArgumentException('non-nullable roles cannot be null');
        }
        $this->container['roles'] = $roles;

        return $this;
    }

    /**
     * Gets user
     *
     * @return \OpenAPI\Client\Model\UserResponse
     */
    public function getUser(): \OpenAPI\Client\Model\UserResponse
    {
        return $this->container['user'];
    }

    /**
     * Sets user
     *
     * @param \OpenAPI\Client\Model\UserResponse $user user
     *
     * @return $this
     */
    public function setUser(\OpenAPI\Client\Model\UserResponse $user): static
    {
        if (is_null($user)) {
            throw new InvalidArgumentException('non-nullable user cannot be null');
        }
        $this->container['user'] = $user;

        return $this;
    }

    /**
     * Gets mute
     *
     * @return bool
     */
    public function getMute(): bool
    {
        return $this->container['mute'];
    }

    /**
     * Sets mute
     *
     * @param bool $mute mute
     *
     * @return $this
     */
    public function setMute(bool $mute): static
    {
        if (is_null($mute)) {
            throw new InvalidArgumentException('non-nullable mute cannot be null');
        }
        $this->container['mute'] = $mute;

        return $this;
    }

    /**
     * Gets deaf
     *
     * @return bool
     */
    public function getDeaf(): bool
    {
        return $this->container['deaf'];
    }

    /**
     * Sets deaf
     *
     * @param bool $deaf deaf
     *
     * @return $this
     */
    public function setDeaf(bool $deaf): static
    {
        if (is_null($deaf)) {
            throw new InvalidArgumentException('non-nullable deaf cannot be null');
        }
        $this->container['deaf'] = $deaf;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


